apiVersion: v1
kind: Secret
metadata:
  name: localstack-aws-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-aws-creds
      key: credentials
  endpoint:
    url:
      type: Static
      static: http://localstack.crossplane-demo.svc.cluster.local:4566
    services:
      - s3
  s3_use_path_style: true
  skip_metadata_api_check: true
  skip_credentials_validation: true
  skip_requesting_account_id: true
